language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp lint:scripts